### ISSUE TITLE
 'CachedPackage' object has no attribute 'remove'

### ISSUE THREAD

**Issue by spinatelli** [spacy-io/sputnik#3]
Hi,
I'm trying to understand how Sputnik works and while trying out a slightly adapted version of this [code](https://github.com/spacy-io/sense2vec/blob/master/sense2vec/download.py), I encountered this exception:

```
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    plac.call(main)
  File "/usr/local/lib/python3.5/site-packages/plac_core.py", line 309, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "/usr/local/lib/python3.5/site-packages/plac_core.py", line 195, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "pd.py", line 28, in main
    package = sputnik.install(appname, version, model, None, "http://localhost")
  File "/usr/local/lib/python3.5/site-packages/sputnik/__init__.py", line 37, in install
    index.update()
  File "/usr/local/lib/python3.5/site-packages/sputnik/index.py", line 110, in update
    package.remove()
AttributeError: 'CachedPackage' object has no attribute 'remove'
```
I just started playing around with Sputnik, but I guess if the intention of line 109-110 is to clear all the leftover packages from the cache, maybe using `cache.remove(package)` might do it?
Cheers!

**Comment by phdowling** [comment]
I'm getting the same error when trying to run `python -m spacy.en.download`, in the same env as issue #395 - I'm honestly not sure what even changed in the environment that I am now getting this error rather than the one reported there. 
If I run `python -m spacy.en.download --force`, things are at first, but spacy complains:
`RuntimeError: Installed model is not compatible with spaCy version. Please run 'python -m spacy.en.download --force' to install latest compatible model.
`
